/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.magapinv.www.interfacesmagap;

import com.magapinv.www.accesodatos.AccesoDatos;
import com.magapinv.www.accesodatos.ConjuntoResultado;
import com.magapinv.www.logicanegocios.clases.Estado_ac;
import com.magapinv.www.logicanegocios.clases.Funcionario;
import com.magapinv.www.logicanegocios.funciones.FEstado_ac;
import com.magapinv.www.logicanegocios.funciones.FFuncionario;
import com.magapinv.www.logicanegocios.funciones.FFuncionario_Rol;
import com.magapinv.www.reportes.Estado_Articulo;
import com.magapinv.www.reportes.Movimiento_Articulo;
import com.magapinv.www.reportes.Stock_Articulos;
import com.magapinv.www.reportes.Stock_Codigo;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mario
 */
public class Reportes extends javax.swing.JFrame {
        DefaultListModel modelo= new DefaultListModel();
        DefaultListModel modelo2= new DefaultListModel();
        DefaultListModel modelo3= new DefaultListModel();  
        DefaultListModel modelo_funcionario_cedula_reporte_mensual= new DefaultListModel();
   private Stock_Articulos jasper;
   private Stock_Codigo jasper1;
   private Estado_Articulo jasper2;
   private Movimiento_Articulo jasper3;
    public Reportes() {
        initComponents();
        cmbestadoInventario_reporte.removeAllItems();
        jasper=new Stock_Articulos();
        jasper1=new Stock_Codigo();
        jasper2=new Estado_Articulo();
        jasper3=new Movimiento_Articulo();
        
        modelo.clear();
        modelo2.clear();
        modelo3.clear();
        
        try {
            for(Estado_ac e: FEstado_ac.obtenerTodoslosEstado_ac()){
                  
                    cmbestadoInventario_reporte.addItem(e.getNombre_estado());
                    
                }
        } catch (Exception ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnReporte_Stock_Codigo = new javax.swing.JButton();
        txt_BuscarModificarArticulo1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListModificarEquipo = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListModificarEquipo2 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListModificarEquipo3 = new javax.swing.JList();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cmbestadoInventario_reporte = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        btnReporte_Articulo_Estado = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btn_grafico_estado = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        btnReporte_Stock_Completo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel30 = new javax.swing.JLabel();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        fecha_final = new com.toedter.calendar.JDateChooser();
        txt_BuscaFuncionarioReporteMensual = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jListFuncionarioReporteMensual = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Stock por código artículo"));

        btnReporte_Stock_Codigo.setText("Reporte Stock");
        btnReporte_Stock_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte_Stock_CodigoActionPerformed(evt);
            }
        });
        btnReporte_Stock_Codigo.setBounds(30, 160, 170, 40);
        jLayeredPane1.add(btnReporte_Stock_Codigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_BuscarModificarArticulo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarModificarArticulo1KeyReleased(evt);
            }
        });
        txt_BuscarModificarArticulo1.setBounds(20, 40, 240, 30);
        jLayeredPane1.add(txt_BuscarModificarArticulo1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jListModificarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListModificarEquipoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListModificarEquipo);

        jScrollPane4.setBounds(300, 20, 170, 140);
        jLayeredPane1.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jListModificarEquipo2.setEnabled(false);
        jScrollPane6.setViewportView(jListModificarEquipo2);

        jScrollPane6.setBounds(490, 20, 170, 140);
        jLayeredPane1.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jListModificarEquipo3.setEnabled(false);
        jScrollPane7.setViewportView(jListModificarEquipo3);

        jScrollPane7.setBounds(680, 20, 170, 140);
        jLayeredPane1.add(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar artículo por estado"));

        cmbestadoInventario_reporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbestadoInventario_reporte.setBounds(150, 40, 200, 30);
        jLayeredPane2.add(cmbestadoInventario_reporte, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setText("Estado");
        jLabel19.setBounds(30, 40, 100, 20);
        jLayeredPane2.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnReporte_Articulo_Estado.setText("Reporte Artículo Estado");
        btnReporte_Articulo_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte_Articulo_EstadoActionPerformed(evt);
            }
        });
        btnReporte_Articulo_Estado.setBounds(210, 90, 147, 40);
        jLayeredPane2.add(btnReporte_Articulo_Estado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráfico Estado de artículos"));

        btn_grafico_estado.setText("Visualizar Cantidad artículo y estado");
        btn_grafico_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grafico_estadoActionPerformed(evt);
            }
        });
        btn_grafico_estado.setBounds(20, 50, 205, 40);
        jLayeredPane3.add(btn_grafico_estado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar todos los artículos del Inventario"));

        btnReporte_Stock_Completo.setText("Reporte Stock Inventario");
        btnReporte_Stock_Completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte_Stock_CompletoActionPerformed(evt);
            }
        });
        btnReporte_Stock_Completo.setBounds(10, 50, 200, 40);
        jLayeredPane4.add(btnReporte_Stock_Completo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/magapinv/www/interfacesmagap/recursos/LOGO SSTRA1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/magapinv/www/interfacesmagap/recursos/logo_magap.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("REPORTES");

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte mensual de Funcionarios"));

        jLabel30.setText("Seleccionar la fecha Inicio");
        jLabel30.setBounds(490, 20, 140, 14);
        jLayeredPane5.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fecha_inicio.setBounds(490, 40, 160, 30);
        jLayeredPane5.add(fecha_inicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setText("Seleccionar la fecha Fin");
        jLabel31.setBounds(690, 20, 140, 14);
        jLayeredPane5.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fecha_final.setBounds(690, 40, 160, 30);
        jLayeredPane5.add(fecha_final, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_BuscaFuncionarioReporteMensual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscaFuncionarioReporteMensualKeyReleased(evt);
            }
        });
        txt_BuscaFuncionarioReporteMensual.setBounds(20, 40, 160, 30);
        jLayeredPane5.add(txt_BuscaFuncionarioReporteMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel60.setText("Ingrese la CEDULA del funcionario");
        jLabel60.setBounds(20, 20, 163, 14);
        jLayeredPane5.add(jLabel60, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setText("Números de cédula ");
        jLabel24.setBounds(210, 20, 180, 14);
        jLayeredPane5.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jListFuncionarioReporteMensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jListFuncionarioReporteMensualMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListFuncionarioReporteMensualMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(jListFuncionarioReporteMensual);

        jScrollPane18.setBounds(210, 40, 180, 140);
        jLayeredPane5.add(jScrollPane18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(720, 110, 140, 40);
        jLayeredPane5.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu2.setText("Ayuda");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setText("A cerca de ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addComponent(jLayeredPane5))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
     
     
    
    
    
    private void btnReporte_Stock_CompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte_Stock_CompletoActionPerformed
      
            // TODO add your handling code here:
          jasper.ejecutarReporte1();
       
    }//GEN-LAST:event_btnReporte_Stock_CompletoActionPerformed

    private void txt_BuscarModificarArticulo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarModificarArticulo1KeyReleased
        // TODO add your handling code here:
        if (txt_BuscarModificarArticulo1.getText().isEmpty()){
            modelo.clear();
            modelo2.clear();
            modelo3.clear();
        }
        else
        {

            try {
                String cad = txt_BuscarModificarArticulo1.getText();
                String sql ="Select * from bodega.inventario where id_equipo like '"+
                cad+"%'";
                ConjuntoResultado cres = AccesoDatos.ejecutaQuery(sql);

                modelo.clear();
                modelo2.clear();
                modelo3.clear();

                while (cres.next()){

                    modelo.addElement(cres.getObject(1));
                    modelo2.addElement(cres.getObject(2));
                    modelo3.addElement(cres.getObject(3));

                }

                this.jListModificarEquipo.setModel(modelo);
                this.jListModificarEquipo2.setModel(modelo2);
                this.jListModificarEquipo3.setModel(modelo3);

            }
            catch (Exception ex) {
                Logger.getLogger(Ingresar_Unidad.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());

            }
        }
    }//GEN-LAST:event_txt_BuscarModificarArticulo1KeyReleased

    private void jListModificarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListModificarEquipoMouseClicked

        try {

            txt_BuscarModificarArticulo1.setText(jListModificarEquipo.getSelectedValue().toString());
        } catch (Exception ex) {
            Logger.getLogger(Ingresar_Unidad.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jListModificarEquipoMouseClicked

    private void btnReporte_Stock_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte_Stock_CodigoActionPerformed
        // TODO add your handling code here:
        String codigo_eq=txt_BuscarModificarArticulo1.getText();
        jasper1.ejecutarReporte_Stock_Codigo(codigo_eq);
    }//GEN-LAST:event_btnReporte_Stock_CodigoActionPerformed

    private void btnReporte_Articulo_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte_Articulo_EstadoActionPerformed
        // TODO add your handling code here:
        String estado_articulo = cmbestadoInventario_reporte.getSelectedItem().toString();
        jasper2.ejecutarReporte_Estado_Articulo(estado_articulo);
    }//GEN-LAST:event_btnReporte_Articulo_EstadoActionPerformed

    private void btn_grafico_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grafico_estadoActionPerformed
        // TODO add your handling code here:
         jasper2.ejecutarReporte_Estado_Articulo_Grafico();
    }//GEN-LAST:event_btn_grafico_estadoActionPerformed

    private void txt_BuscaFuncionarioReporteMensualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscaFuncionarioReporteMensualKeyReleased
        // TODO add your handling code here:
        if (txt_BuscaFuncionarioReporteMensual.getText().isEmpty()){
            modelo_funcionario_cedula_reporte_mensual.clear();
        }
        else
        {

            try {
                String cad = txt_BuscaFuncionarioReporteMensual.getText();
                String sql ="Select * from bodega.funcionario_rol where numero_cedula like '"+
                cad+"%'";
                ConjuntoResultado cres = AccesoDatos.ejecutaQuery(sql);

                modelo_funcionario_cedula_reporte_mensual.clear();

                while (cres.next()){

                    modelo_funcionario_cedula_reporte_mensual.addElement(cres.getObject(0));
                }

                this.jListFuncionarioReporteMensual.setModel(modelo_funcionario_cedula_reporte_mensual);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());

            }
        }
    }//GEN-LAST:event_txt_BuscaFuncionarioReporteMensualKeyReleased

    private void jListFuncionarioReporteMensualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListFuncionarioReporteMensualMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jListFuncionarioReporteMensualMouseEntered

    private void jListFuncionarioReporteMensualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListFuncionarioReporteMensualMouseClicked
        txt_BuscaFuncionarioReporteMensual.setText(jListFuncionarioReporteMensual.getSelectedValue().toString());
    }//GEN-LAST:event_jListFuncionarioReporteMensualMouseClicked

     public static java.sql.Date formatoFecha(String fechaBodega) throws ParseException{
    
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            Date dateStr = formatter.parse(fechaBodega);

            java.sql.Date sqlDate = new java.sql.Date(dateStr.getTime());
        return sqlDate;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String fechainicio = new SimpleDateFormat("yyyy-MM-dd").format(fecha_inicio.getDate());
            String fechafin = new SimpleDateFormat("yyyy-MM-dd").format(fecha_final.getDate());
            
                java.sql.Date fecha;
                java.sql.Date fecha1;
                
                    fecha = formatoFecha(fechainicio);
                    fecha1 = formatoFecha(fechafin);
                    String nombre_bodega = FFuncionario.obtenerFuncionario_xrol().getNombres().trim()+" "+FFuncionario.obtenerFuncionario_xrol().getApellidos().trim();    
                    String recibe =FFuncionario.obtenerFuncionario_xcodigo(txt_BuscaFuncionarioReporteMensual.getText()).getNombres().trim()+" "+FFuncionario.obtenerFuncionario_xcodigo(txt_BuscaFuncionarioReporteMensual.getText()).getApellidos().trim();
                    String nombre_acta ="ENTREGA/RECEPCION";
                    String cargo_funcionario_mensual=FFuncionario_Rol.obtenerFuncionarioRol_xcodigo_reporte(txt_BuscaFuncionarioReporteMensual.getText()).getId_rol().getNombre_rol().trim();
                       
         jasper3.ejecutarReporte_Funcionario_Mensual(txt_BuscaFuncionarioReporteMensual.getText(),fecha,fecha1, recibe,nombre_bodega,cargo_funcionario_mensual);
        } catch (Exception ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        try{
            File directorio = new File("temp"); //Creas un nuevo directorio a nivel de tu jar.
            directorio.mkdirs();
            directorio.setWritable(true);
            //copias la direccion
            String archivo = directorio.getCanonicalPath() + File.pathSeparator + "erfc.pdf";
            //nuevo archivo en esa direccion
            File temp = new File(archivo);
            InputStream is = this.getClass().getResourceAsStream("/com/magapinv/www/interfacesmagap/recursos/Manual_de_Director_subsecretaria_del_sistema_de_inventario_Automatizado_SINA.pdf");
            FileOutputStream archivoDestino = new FileOutputStream(temp);
            FileWriter fw = new FileWriter(temp);
            byte[] buffer = new byte[512*1024];
            //lees el archivo hasta que se acabe...
            int nbLectura;
            while ((nbLectura = is.read(buffer)) != -1)
                archivoDestino.write(buffer, 0, nbLectura);
            //cierras el archivo,el inputS y el FileW
            fw.close();
            archivoDestino.close();
            is.close();
            //abres el archivo temporal
            Desktop.getDesktop().open(temp);
        } catch (IOException ex) {
            System.out.println("Problema abriendo el pdf de erfc");
        }
      

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        acercade rep = new acercade();
        rep.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte_Articulo_Estado;
    private javax.swing.JButton btnReporte_Stock_Codigo;
    private javax.swing.JButton btnReporte_Stock_Completo;
    private javax.swing.JButton btn_grafico_estado;
    private javax.swing.JComboBox cmbestadoInventario_reporte;
    private com.toedter.calendar.JDateChooser fecha_final;
    private com.toedter.calendar.JDateChooser fecha_inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JList jListFuncionarioReporteMensual;
    private javax.swing.JList jListModificarEquipo;
    private javax.swing.JList jListModificarEquipo2;
    private javax.swing.JList jListModificarEquipo3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField txt_BuscaFuncionarioReporteMensual;
    private javax.swing.JTextField txt_BuscarModificarArticulo1;
    // End of variables declaration//GEN-END:variables
}
